/*
  Tool registry is the single source of truth for JSON Services catalog, routing,
  UI option rendering, and execution behavior in the shared workspace.
*/
import type {
  JsonToolCategory,
  JsonToolDefinition,
  JsonToolOptionField,
} from "../../types/jsonTools";

export const JSON_TOOL_CATEGORIES: JsonToolCategory[] = [
  "Format",
  "Convert",
  "Analyze",
  "Compare",
  "Structure",
  "Protect",
  "Visual",
];

const simpleIndent: JsonToolOptionField = {
  key: "indent",
  label: "Indent",
  type: "number",
  min: 0,
  max: 8,
  defaultValue: 2,
};

export const JSON_TOOLS: JsonToolDefinition[] = [
  {
    id: "beautify-json",
    title: "Beautify JSON",
    category: "Format",
    description: "Pretty-print JSON with configurable indentation.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "minify-json",
    title: "Minify JSON",
    category: "Format",
    description: "Remove all unnecessary whitespace from JSON.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "validate-json",
    title: "Validate JSON",
    category: "Format",
    description: "Validate syntax and optionally normalize output.",
    optionsSchema: [
      {
        key: "mode",
        label: "Output mode",
        type: "select",
        defaultValue: "message",
        options: [
          { label: "Validation message", value: "message" },
          { label: "Normalized JSON", value: "normalized" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "json-to-yaml",
    title: "Convert JSON to YAML",
    category: "Convert",
    description: "Transform JSON into YAML format.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "yaml",
  },
  {
    id: "yaml-to-json",
    title: "Convert YAML to JSON",
    category: "Convert",
    description: "Transform YAML input into formatted JSON.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "YAML Input",
  },
  {
    id: "json-to-xml",
    title: "Convert JSON to XML",
    category: "Convert",
    description: "Transform JSON into XML with custom root name.",
    optionsSchema: [
      {
        key: "rootName",
        label: "Root element",
        type: "text",
        defaultValue: "root",
      },
    ],
    outputKind: "text",
    fileExtension: "xml",
  },
  {
    id: "xml-to-json",
    title: "Convert XML to JSON",
    category: "Convert",
    description: "Parse XML into JSON structure.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "XML Input",
  },
  {
    id: "json-to-csv",
    title: "Convert JSON to CSV",
    category: "Convert",
    description: "Convert arrays of objects into CSV rows.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "csv",
  },
  {
    id: "csv-to-json",
    title: "Convert CSV to JSON",
    category: "Convert",
    description: "Parse CSV records into JSON rows.",
    optionsSchema: [
      {
        key: "hasHeader",
        label: "First row is header",
        type: "checkbox",
        defaultValue: true,
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "CSV Input",
  },
  {
    id: "json-to-sql-insert",
    title: "Convert JSON to SQL Insert",
    category: "Convert",
    description: "Generate SQL INSERT statements from JSON objects.",
    optionsSchema: [
      { key: "tableName", label: "Table name", type: "text", defaultValue: "records" },
      {
        key: "formatSql",
        label: "Format SQL",
        type: "checkbox",
        defaultValue: true,
      },
    ],
    outputKind: "text",
    fileExtension: "sql",
  },
  {
    id: "sql-insert-to-json",
    title: "Convert SQL Insert to JSON",
    category: "Convert",
    description: "Extract rows from INSERT statements as JSON.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "SQL INSERT Input",
  },
  {
    id: "json-to-sql-query",
    title: "Convert JSON to SQL Query",
    category: "Convert",
    description: "Generate SQL SELECT/UPDATE/DELETE query from key-value JSON.",
    optionsSchema: [
      { key: "tableName", label: "Table name", type: "text", defaultValue: "records" },
      {
        key: "queryMode",
        label: "Query mode",
        type: "select",
        defaultValue: "select",
        options: [
          { label: "SELECT", value: "select" },
          { label: "UPDATE", value: "update" },
          { label: "DELETE", value: "delete" },
        ],
      },
    ],
    outputKind: "text",
    fileExtension: "sql",
  },
  {
    id: "json-to-base64",
    title: "Convert JSON to Base64",
    category: "Convert",
    description: "Encode minified JSON payload into Base64.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "base64-to-json",
    title: "Convert Base64 to JSON",
    category: "Convert",
    description: "Decode Base64 payload into JSON.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "Base64 Input",
  },
  {
    id: "json-to-bson",
    title: "Convert JSON to BSON",
    category: "Convert",
    description: "Serialize JSON into BSON and emit Base64 text.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "bson-to-json",
    title: "Convert BSON to JSON",
    category: "Convert",
    description: "Deserialize Base64 BSON data into JSON.",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    inputLabel: "Base64 BSON Input",
  },
  {
    id: "json-stringify",
    title: "JSON Stringify",
    category: "Format",
    description: "Escape full input into one JSON string literal.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
    inputLabel: "Text Input",
  },
  {
    id: "json-stripslashes",
    title: "JSON Stripslashes",
    category: "Format",
    description: "Strip escape backslashes from text snippets.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
    inputLabel: "Escaped Text Input",
  },
  {
    id: "json-escape",
    title: "JSON Escape",
    category: "Format",
    description: "Escape text for safe JSON string embedding.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
    inputLabel: "Text Input",
  },
  {
    id: "json-unescape",
    title: "JSON Unescape",
    category: "Format",
    description: "Unescape escaped JSON string text.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
    inputLabel: "Escaped Text Input",
  },
  {
    id: "sort-json",
    title: "Sort JSON",
    category: "Structure",
    description: "Sort object keys recursively and optionally sort arrays.",
    optionsSchema: [
      {
        key: "arraySortMode",
        label: "Array sort",
        type: "select",
        defaultValue: "none",
        options: [
          { label: "Do not sort", value: "none" },
          { label: "Ascending", value: "asc" },
          { label: "Descending", value: "desc" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "filter-json",
    title: "Filter JSON",
    category: "Analyze",
    description: "Filter JSON by JSONPath expression.",
    optionsSchema: [
      { key: "path", label: "JSONPath", type: "text", defaultValue: "$" },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "count-json-objects",
    title: "Count JSON Objects",
    category: "Analyze",
    description: "Count object nodes and top-level array length.",
    optionsSchema: [],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "find-duplicate-json-objects",
    title: "Find Duplicate JSON Objects",
    category: "Analyze",
    description: "Detect duplicate entries in JSON arrays.",
    optionsSchema: [
      {
        key: "outputMode",
        label: "Output mode",
        type: "select",
        defaultValue: "details",
        options: [
          { label: "Detailed list", value: "details" },
          { label: "Summary only", value: "summary" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "compare-json",
    title: "Compare JSON",
    category: "Compare",
    description: "Check equivalence between two JSON documents.",
    secondaryInputMode: "text",
    optionsSchema: [
      {
        key: "outputMode",
        label: "Output mode",
        type: "select",
        defaultValue: "summary",
        options: [
          { label: "Summary", value: "summary" },
          { label: "Structured", value: "structured" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "diff-json",
    title: "Diff JSON",
    category: "Compare",
    description: "Generate JSON Patch or delta between two JSON documents.",
    secondaryInputMode: "text",
    optionsSchema: [
      {
        key: "mode",
        label: "Diff mode",
        type: "select",
        defaultValue: "patch",
        options: [
          { label: "JSON Patch", value: "patch" },
          { label: "Delta", value: "delta" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "patch-json",
    title: "Patch JSON",
    category: "Compare",
    description: "Apply JSON Patch operations to a base JSON document.",
    secondaryInputMode: "text",
    optionsSchema: [simpleIndent],
    outputKind: "text",
    fileExtension: "json",
    secondaryInputLabel: "JSON Patch Input",
  },
  {
    id: "flatten-json",
    title: "Flatten JSON",
    category: "Structure",
    description: "Flatten nested JSON into separator-based paths.",
    optionsSchema: [
      { key: "separator", label: "Separator", type: "text", defaultValue: "." },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "unflatten-json",
    title: "Unflatten JSON",
    category: "Structure",
    description: "Rebuild nested JSON from flattened key paths.",
    optionsSchema: [
      { key: "separator", label: "Separator", type: "text", defaultValue: "." },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "repair-json",
    title: "Repair JSON",
    category: "Structure",
    description: "Repair malformed JSON text using tolerant parser heuristics.",
    optionsSchema: [
      {
        key: "outputMode",
        label: "Output mode",
        type: "select",
        defaultValue: "pretty",
        options: [
          { label: "Pretty JSON", value: "pretty" },
          { label: "Raw repaired", value: "raw" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "redact-json",
    title: "Redact JSON",
    category: "Protect",
    description: "Redact sensitive keys recursively from JSON payloads.",
    optionsSchema: [
      {
        key: "keys",
        label: "Keys to redact",
        type: "text",
        defaultValue: "password,token,secret,apiKey",
      },
      {
        key: "replacement",
        label: "Replacement text",
        type: "text",
        defaultValue: "[REDACTED]",
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "obfuscate-json",
    title: "Obfuscate JSON",
    category: "Protect",
    description: "Obfuscate string and numeric values for safe sharing.",
    optionsSchema: [
      {
        key: "mode",
        label: "Obfuscation mode",
        type: "select",
        defaultValue: "mask",
        options: [
          { label: "Mask", value: "mask" },
          { label: "Reverse", value: "reverse" },
          { label: "Hash-like", value: "hash" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "encode-json",
    title: "Encode JSON",
    category: "Protect",
    description: "Encode JSON in Base64, URI, or HEX representation.",
    optionsSchema: [
      {
        key: "mode",
        label: "Encoding mode",
        type: "select",
        defaultValue: "base64",
        options: [
          { label: "Base64", value: "base64" },
          { label: "URI", value: "uri" },
          { label: "HEX", value: "hex" },
        ],
      },
    ],
    outputKind: "text",
    fileExtension: "txt",
  },
  {
    id: "decode-json",
    title: "Decode JSON",
    category: "Protect",
    description: "Decode Base64, URI, or HEX into JSON.",
    optionsSchema: [
      {
        key: "mode",
        label: "Decoding mode",
        type: "select",
        defaultValue: "base64",
        options: [
          { label: "Base64", value: "base64" },
          { label: "URI", value: "uri" },
          { label: "HEX", value: "hex" },
        ],
      },
      simpleIndent,
    ],
    outputKind: "text",
    fileExtension: "json",
  },
  {
    id: "json-to-image",
    title: "Convert JSON to Image",
    category: "Visual",
    description: "Render formatted JSON into downloadable image.",
    optionsSchema: [
      {
        key: "theme",
        label: "Theme",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      { key: "fontSize", label: "Font size", type: "number", defaultValue: 14, min: 10, max: 22 },
    ],
    outputKind: "visual",
    fileExtension: "png",
  },
  {
    id: "screenshot-json",
    title: "Screenshot JSON",
    category: "Visual",
    description: "Generate screenshot-style JSON image with card framing.",
    optionsSchema: [
      {
        key: "theme",
        label: "Theme",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      { key: "fontSize", label: "Font size", type: "number", defaultValue: 14, min: 10, max: 22 },
      { key: "title", label: "Screenshot title", type: "text", defaultValue: "JSON Preview" },
    ],
    outputKind: "visual",
    fileExtension: "png",
  },
];

export const JSON_TOOL_BY_ID: Record<string, JsonToolDefinition> = Object.fromEntries(
  JSON_TOOLS.map((tool) => [tool.id, tool])
);
